openapi: 3.0.0
info:
  description: '<font size="2" color="red">MIT License</font>'
  title: "Web-Scraping-Api"
  contact:
    name: Erlan Lucio
    url: https://github.com/lucioerlan
  version: '1.0'
servers:
- url: http://localhost:5000/api
  variables: {}
paths:
  /jobs:
    get:
      tags:
      - Misc
      summary: SCRAPING JOBS
      operationId: SCRAPINGJOBS
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''
